server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://35.244.43.54:3306/hospital_db?useSSL=false&serverTimezone=UTC
    username: drpankajsurgicalpath_database	
    password: Gwlg@2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
